#!/bin/bash

# Version 0.5 October 26, 2016
### BEGIN INIT INFO
# Provides:          alphamonagent
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $network $named $portmap $syslog $remote_fs
# Required-Stop:     $remote_fs $syslog 
# Short-Description: Alphamon Pi Agent
#
### END INIT INFO

# Author: Sameer Chandra <tsameerc@gmail.com>
#
start() {
    # code to start app comes here
    nohup http-client > /tmp/alphamonagent.log 2>&1 &
}

stop() {
    # code to stop app comes here 
      echo "hello alphamonagent here" 
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
