#!/bin/bash

# Source function library.


start() {
    # code to start app comes here
    echo "hello alphamonagent here" 
}

stop() {
    # code to stop app comes here 
      echo "hello alphamonagent here" 
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
